version: '3'

services:

  db:
    build:
      context: database
    container_name: db
    hostname: db
    restart: always
    tty: true
    command: --init-file /docker-entrypoint-initdb.d/CreateDatabase.sql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    hostname: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr//src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - node-network
    depends_on:
      - db
  
  reverseproxy:
    build: 
      context: nginx
    container_name: reverseproxy
    tty: true
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app
 
 
networks:
  node-network:
